import uuid

import mysql.connector
from mysql.connector import Error
from dotenv import load_dotenv
import os

# Charger les variables d'environnement depuis .env
load_dotenv()

DB_HOST = os.getenv('DB_HOST')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_NAME = os.getenv('DB_NAME')


try:
    connection = mysql.connector.connect(
        host=DB_HOST,
        user=DB_USER,
        password=DB_PASSWORD,
        database=DB_NAME
    )

    if connection.is_connected():
        cursor = connection.cursor()

        requete_categorie = """
               INSERT INTO categorie_fidelite (id, nom, seuil_minimum) VALUES
                (1, "Cassette Basique",  0),
                (2, "VHS Classique",  100),
                (3, "Édition Collector",  500),
                (4, "LaserDisc Élite", 1000),
                (5, "Master du Magnétoscope", 2500);
                """

        cursor.execute(requete_categorie)
        connection.commit()
        print(f"{cursor.rowcount} catégories de fidélité ont été insérées avec succès !")

        # seed pour les produits
        films = [
            # Films originaux
            ('123e4567-e89b-12d3-a456-426614174000', "Science-fiction", "La Guerre des Étoiles",
             "Un jeune fermier se joint à une rébellion contre un Empire maléfique.", 22.99, 121, 1977, 15),
            ('a3b55932-446d-44ac-a2be-2f1ffc7b8b28', "Aventure", "Les Aventuriers de l'arche perdue",
             "Indiana Jones cherche l'Arche d'alliance avant les nazis.", 20.99, 115, 1981, 5),
            ('a2c5853e-c7fd-4c20-8991-4fbe0a29aece', "Animation", "Le Roi Lion",
             "Un jeune lion doit retrouver son royaume après la mort de son père.", 16.99, 89, 1994, 20),
            ('aa9e40c3-2d8f-42cf-85e9-1b9861449571', "Drame", "Le Fabuleux Destin d'Amélie Poulain",
             "Amélie, une jeune serveuse parisienne, décide de changer la vie des autres.", 18.99, 122, 2001, 8),
            ('b16ace2b-00d4-4f27-a25f-e0bc090ea85a', "Aventure", "Jurassic Park",
             "Des dinosaures ramenés à la vie terrorisent un parc à thème.", 12.99, 127, 1993, 7),
            ('e53912b5-5c8b-4c6e-9140-45d8ede27ad3', "Drame", "Titanic",
             "Une romance naît entre deux passagers de classes différentes à bord d'un navire en perdition.", 14.99,
             195, 1997, 10),
            ('1d724a84-cdea-4195-b64a-5765ec6bb0de', "Science-fiction", "Inception",
             "Un voleur infiltre les rêves pour dérober des secrets et réimplanter des idées.", 18.99, 148, 2010, 12),
            ('df6381bb-3926-47e9-8d1f-2393182865dc', "Aventure", "Retour vers le Futur",
             "Un adolescent voyage dans le temps avec une voiture modifiée.", 17.99, 116, 1985, 6),
            ('ad0c8fc5-8d15-4b9d-a2f3-9d6fc11ff0de', "Crime", "Pulp Fiction",
             "Une série d'histoires criminelles entremêlées dans Los Angeles.", 14.99, 154, 1994, 8),
            ('c65aaa64-1049-47eb-9c31-b27a6e209f24', "Drame", "Rocky",
             "Un boxeur amateur de Philadelphie tente sa chance contre un champion.", 13.99, 120, 1976, 10),

            # Films ajoutés
            (str(uuid.uuid4()), "Animation", "Toy Story",
             "Des jouets qui prennent vie quand les humains ne regardent pas.", 15.99, 81, 1995, 18),
            (str(uuid.uuid4()), "Action", "Die Hard",
             "Un policier combat seul des terroristes dans un gratte-ciel.", 13.99, 132, 1988, 9),
            (str(uuid.uuid4()), "Science-fiction", "Matrix",
             "Un programmeur découvre que la réalité est une simulation.", 16.99, 136, 1999, 14),
            (str(uuid.uuid4()), "Comédie", "Le Dîner de Cons",
             "Un éditeur invite un idiot à dîner pour se moquer de lui, mais tout tourne mal.", 12.99, 80, 1998, 6),
            (str(uuid.uuid4()), "Horreur", "Shining",
             "Un écrivain devient fou dans un hôtel isolé pendant l'hiver.", 14.99, 146, 1980, 8),
            (str(uuid.uuid4()), "Thriller", "Le Silence des Agneaux",
             "Une agente du FBI demande l'aide d'un tueur en série pour en capturer un autre.", 15.99, 118, 1991, 7),
            (str(uuid.uuid4()), "Drame", "Forrest Gump",
             "La vie d'un homme simple d'esprit qui influence inconsciemment plusieurs événements historiques.", 14.99,
             142, 1994, 12),
            (str(uuid.uuid4()), "Fantastique", "Le Seigneur des Anneaux: La Communauté de l'Anneau",
             "Un hobbit entreprend une quête pour détruire un anneau maléfique.", 19.99, 178, 2001, 15),
            (str(uuid.uuid4()), "Animation", "La Belle et la Bête",
             "Une jeune femme tombe amoureuse d'un prince transformé en bête.", 15.99, 84, 1991, 10),
            (str(uuid.uuid4()), "Comédie", "Le Grand Lebowski",
             "Un fainéant est confondu avec un millionnaire du même nom.", 13.99, 117, 1998, 6),
            (str(uuid.uuid4()), "Science-fiction", "Blade Runner",
             "Un détective traque des robots humanoïdes dans un futur dystopique.", 17.99, 117, 1982, 9),
            (str(uuid.uuid4()), "Drame", "Les Évadés",
             "Un homme injustement emprisonné bâtit une amitié avec un autre détenu tout en planifiant son évasion.",
             14.99, 142, 1994, 8),
            (str(uuid.uuid4()), "Crime", "Le Parrain",
             "Le chef vieillissant d'une famille mafieuse transfère le contrôle à son fils réticent.", 18.99, 175, 1972,
             11),
            (str(uuid.uuid4()), "Comédie", "Intouchables",
             "Un aristocrate tétraplégique embauche un jeune de banlieue comme aide-soignant.", 16.99, 112, 2011, 14),
            (str(uuid.uuid4()), "Western", "Le Bon, la Brute et le Truand",
             "Trois hommes recherchent un trésor pendant la Guerre civile américaine.", 13.99, 161, 1966, 5),
            (str(uuid.uuid4()), "Aventure", "Pirates des Caraïbes: La Malédiction du Black Pearl",
             "Un forgeron s'allie à un pirate excentrique pour sauver la femme qu'il aime.", 15.99, 143, 2003, 12),
            (str(uuid.uuid4()), "Science-fiction", "E.T. l'extra-terrestre",
             "Un jeune garçon se lie d'amitié avec un extraterrestre perdu sur Terre.", 14.99, 115, 1982, 9),
            (str(uuid.uuid4()), "Animation", "Shrek",
             "Un ogre part en quête pour délivrer une princesse et sauver son marais.", 13.99, 90, 2001, 15),
            (str(uuid.uuid4()), "Drame", "La Liste de Schindler",
             "Un homme d'affaires allemand sauve des Juifs pendant l'Holocauste.", 16.99, 195, 1993, 7),
            (str(uuid.uuid4()), "Comédie", "La Vie est Belle",
             "Un père utilise son imagination pour protéger son fils des horreurs d'un camp de concentration.", 15.99,
             116, 1997, 6),
            (str(uuid.uuid4()), "Action", "Gladiator",
             "Un général romain devenu esclave cherche vengeance contre l'empereur corrompu.", 16.99, 155, 2000, 10),
            (str(uuid.uuid4()), "Thriller", "Fight Club",
             "Un homme insomniaque et un vendeur de savon créent un club de combat clandestin.", 14.99, 139, 1999, 8),
            (str(uuid.uuid4()), "Animation", "Le Voyage de Chihiro",
             "Une fillette se retrouve dans un monde fantastique peuplé de divinités et d'esprits.", 17.99, 125, 2001,
             11),
            (str(uuid.uuid4()), "Drame", "Gran Torino",
             "Un vétéran de guerre développe une relation improbable avec ses voisins Hmong.", 13.99, 116, 2008, 7),
            (str(uuid.uuid4()), "Science-fiction", "Interstellar",
             "Des explorateurs voyagent à travers un trou de ver pour assurer la survie de l'humanité.", 18.99, 169,
             2014, 13),
            (str(uuid.uuid4()), "Thriller", "The Dark Knight",
             "Batman affronte un criminel anarchiste connu sous le nom du Joker.", 17.99, 152, 2008, 15),
            (str(uuid.uuid4()), "Animation", "WALL-E",
             "Un robot solitaire sur Terre rencontre un robot sophistiqué et tombe amoureux.", 15.99, 98, 2008, 9),
            (str(uuid.uuid4()), "Comédie", "OSS 117: Le Caire, nid d'espions",
             "Un agent secret français arrogant et maladroit est envoyé en mission en Égypte.", 14.99, 99, 2006, 8),
            (str(uuid.uuid4()), "Drame", "La Ligne verte",
             "Un gardien de prison découvre qu'un condamné à mort possède un don miraculeux.", 16.99, 189, 1999, 6),
            (str(uuid.uuid4()), "Action", "Léon",
             "Un tueur à gages prend sous son aile une jeune fille après le meurtre de sa famille.", 15.99, 110, 1994,
             7),
            (str(uuid.uuid4()), "Comédie musicale", "La La Land",
             "Une actrice et un musicien tombent amoureux à Los Angeles tout en poursuivant leurs rêves.", 17.99, 128,
             2016, 10),
            (str(uuid.uuid4()), "Crime", "Les Affranchis",
             "L'ascension et la chute d'un gangster américain d'origine italienne.", 15.99, 146, 1990, 8),
            (str(uuid.uuid4()), "Animation", "Là-haut",
             "Un vendeur de ballons âgé réalise son rêve de voir l'Amérique du Sud en transformant sa maison en dirigeable.",
             16.99, 96, 2009, 12),
            (str(uuid.uuid4()), "Drame", "Le Pianiste",
             "Un pianiste juif polonais lutte pour survivre à Varsovie pendant la Seconde Guerre mondiale.", 15.99, 150,
             2002, 6),
            (str(uuid.uuid4()), "Comédie", "Les Visiteurs",
             "Un chevalier et son écuyer sont transportés dans les années 1990 par un sort magique.", 13.99, 107, 1993,
             9),
            (str(uuid.uuid4()), "Aventure", "Avatar",
             "Un marine paraplégique est envoyé sur une lune pour infiltrer les autochtones.", 19.99, 162, 2009, 14),
            (str(uuid.uuid4()), "Drame", "Good Will Hunting",
             "Un concierge du MIT se révèle être un génie des mathématiques.", 14.99, 126, 1997, 7),
            (str(uuid.uuid4()), "Science-fiction", "Le Cinquième Élément",
             "Un chauffeur de taxi doit aider une femme mystérieuse à sauver la Terre.", 16.99, 126, 1997, 10),
            (str(uuid.uuid4()), "Horreur", "L'Exorciste",
             "Deux prêtres tentent de sauver une fille possédée par un démon.", 14.99, 122, 1973, 5),
            (str(uuid.uuid4()), "Comédie", "Le Père Noël est une ordure",
             "La soirée de Noël d'une association caritative tourne au cauchemar.", 13.99, 88, 1982, 8),
            (str(uuid.uuid4()), "Thriller", "Usual Suspects",
             "Un criminel raconte à la police une histoire complexe impliquant un mystérieux baron du crime.", 15.99,
             106, 1995, 6),
            (str(uuid.uuid4()), "Drame", "Into the Wild",
             "Un jeune homme abandonne ses possessions pour partir à l'aventure en Alaska.", 16.99, 148, 2007, 9),
            (str(uuid.uuid4()), "Animation", "Les Indestructibles",
             "Une famille de super-héros à la retraite est forcée de reprendre du service.", 15.99, 115, 2004, 11),
            (str(uuid.uuid4()), "Fantastique", "Harry Potter à l'école des sorciers",
             "Un jeune garçon découvre qu'il est un sorcier et entre dans une école de magie.", 17.99, 152, 2001, 15),
            (str(uuid.uuid4()), "Comédie", "Very Bad Trip",
             "Une fête d'enterrement de vie de garçon à Las Vegas dérape complètement.", 14.99, 100, 2009, 8),
            (str(uuid.uuid4()), "Science-fiction", "Alien, le huitième passager",
             "L'équipage d'un vaisseau spatial est traqué par une créature extraterrestre.", 16.99, 117, 1979, 7),
            (str(uuid.uuid4()), "Drame", "American Beauty",
             "Un homme en pleine crise de la quarantaine devient obsédé par l'amie de sa fille.", 15.99, 122, 1999, 6),
            (str(uuid.uuid4()), "Action", "Mad Max: Fury Road",
             "Un survivant dans un monde post-apocalyptique aide un groupe de femmes à échapper à un tyran.", 18.99,
             120, 2015, 10),
            (str(uuid.uuid4()), "Crime", "Reservoir Dogs",
             "Des criminels tentent de déterminer qui parmi eux est un informateur de la police.", 14.99, 99, 1992, 5),
            (str(uuid.uuid4()), "Animation", "Vice-Versa",
             "Les émotions d'une jeune fille tentent de la guider à travers un déménagement difficile.", 16.99, 95,
             2015, 13),
            (str(uuid.uuid4()), "Drame", "Birdman",
             "Un acteur autrefois célèbre pour avoir joué un super-héros tente de monter une pièce à Broadway.", 15.99,
             119, 2014, 7),
            (str(uuid.uuid4()), "Comédie", "La Cité de la peur",
             "La promotion d'un film d'horreur est perturbée par des meurtres similaires à ceux du film.", 13.99, 99,
             1994, 9),
            (str(uuid.uuid4()), "Science-fiction", "2001: l'Odyssée de l'espace",
             "Un voyage dans l'espace mène à une confrontation entre des astronautes et leur ordinateur de bord.",
             17.99, 149, 1968, 6),
            (str(uuid.uuid4()), "Aventure", "Le Hobbit: Un voyage inattendu",
             "Un hobbit est recruté pour accompagner un groupe de nains dans une quête pour récupérer leur royaume.",
             18.99, 169, 2012, 11),
            (str(uuid.uuid4()), "Drame", "Whiplash",
             "Un jeune batteur de jazz est poussé à ses limites par un professeur impitoyable.", 16.99, 107, 2014, 8),
            (str(uuid.uuid4()), "Comédie", "The Truman Show",
             "Un homme découvre que sa vie entière fait l'objet d'une émission de téléréalité.", 14.99, 103, 1998, 7),
            (str(uuid.uuid4()), "Animation", "Princesse Mononoké",
             "Un prince maudit se retrouve impliqué dans une lutte entre les dieux de la forêt et les humains.", 16.99,
             134, 1997, 9),
            (str(uuid.uuid4()), "Thriller", "Seven",
             "Deux détectives traquent un tueur en série qui utilise les sept péchés capitaux comme motifs.", 15.99,
             127, 1995, 6),
            (str(uuid.uuid4()), "Drame", "Midnight Express",
             "Un étudiant américain est emprisonné en Turquie pour contrebande de haschisch.", 14.99, 121, 1978, 5),
            (str(uuid.uuid4()), "Fantastique", "Le Labyrinthe de Pan",
             "Une jeune fille s'échappe dans un monde fantasmagorique pendant la guerre civile espagnole.", 16.99, 118,
             2006, 8),
            (str(uuid.uuid4()), "Comédie", "Bienvenue chez les Ch'tis",
             "Un directeur de poste du sud est muté dans le nord de la France qu'il croit inhospitalier.", 14.99, 106,
             2008, 12),
            (str(uuid.uuid4()), "Science-fiction", "Premier Contact",
             "Une linguiste tente de communiquer avec des extraterrestres qui viennent d'arriver sur Terre.", 17.99,
             116, 2016, 9),
            (str(uuid.uuid4()), "Aventure", "Le Livre de la Jungle",
             "Un jeune garçon élevé par des loups doit échapper à un tigre qui le menace.", 15.99, 106, 2016, 10),
            (str(uuid.uuid4()), "Drame", "Vol au-dessus d'un nid de coucou",
             "Un criminel feint la folie pour éviter la prison et se retrouve dans un hôpital psychiatrique.", 16.99,
             133, 1975, 7),
            (str(uuid.uuid4()), "Comédie", "Qu'est-ce qu'on a fait au Bon Dieu?",
             "Un couple catholique conservateur voit ses filles épouser des hommes d'origines et religions différentes.",
             14.99, 97, 2014, 11),
            (str(uuid.uuid4()), "Animation", "Ratatouille",
             "Un rat passionné de cuisine s'associe avec un jeune commis pour devenir chef à Paris.", 15.99, 111, 2007,
             9),
            (str(uuid.uuid4()), "Action", "John Wick",
             "Un ancien tueur à gages reprend du service après le vol de sa voiture et le meurtre de son chien.", 16.99,
             101, 2014, 10),
            (str(uuid.uuid4()), "Drame", "Le Discours d'un roi",
             "Le roi George VI travaille à surmonter son bégaiement avec l'aide d'un orthophoniste non conventionnel.",
             15.99, 118, 2010, 7),
            (str(uuid.uuid4()), "Thriller", "Gone Girl",
             "Un homme devient le principal suspect quand sa femme disparaît mystérieusement.", 16.99, 149, 2014, 8),
            (str(uuid.uuid4()), "Science-fiction", "Arrival",
             "Une linguiste est recrutée par l'armée pour communiquer avec des extraterrestres.", 17.99, 116, 2016, 9),
            (str(uuid.uuid4()), "Comédie", "Little Miss Sunshine",
             "Une famille dysfonctionnelle entreprend un voyage pour permettre à leur fille de participer à un concours de beauté.",
             14.99, 101, 2006, 6),
            (str(uuid.uuid4()), "Horreur", "Get Out",
             "Un jeune homme noir découvre des secrets troublants lors de sa visite chez les parents de sa petite amie blanche.",
             16.99, 104, 2017, 11),
            (str(uuid.uuid4()), "Animation", "Coco",
             "Un jeune musicien se retrouve accidentellement dans le pays des morts lors de la fête des Morts mexicaine.",
             17.99, 105, 2017, 13),
            (str(uuid.uuid4()), "Drame", "Dallas Buyers Club",
             "Un homme atteint du SIDA commence à faire passer des médicaments non approuvés aux patients.", 15.99, 117,
             2013, 7),
            (str(uuid.uuid4()), "Fantastique", "Twilight",
             "Une adolescente tombe amoureuse d'un vampire.", 14.99, 122, 2008, 9),
            (str(uuid.uuid4()), "Action", "Mission: Impossible",
             "Un agent secret est accusé à tort de trahison et doit prouver son innocence.", 16.99, 110, 1996, 8),
            (str(uuid.uuid4()), "Comédie", "The Mask",
             "Un employé de banque timide se transforme en personnage extravagant grâce à un masque magique.", 13.99,
             97, 1994, 6),
            (str(uuid.uuid4()), "Science-fiction", "Retour vers le Futur 2",
             "Marty McFly doit voyager dans le futur pour empêcher un désastre affectant ses futurs enfants.", 17.99,
             108, 1989, 10),
            (str(uuid.uuid4()), "Drame", "No Country for Old Men",
             "Un homme trouve une mallette pleine d'argent dans le désert et est poursuivi par un tueur implacable.",
             16.99, 122, 2007, 5),
            (str(uuid.uuid4()), "Animation", "Les Minions",
             "Les serviteurs jaunes des méchants cherchent un nouveau maître à servir.", 15.99, 91, 2015, 12),
            (str(uuid.uuid4()), "Thriller", "Memento",
             "Un homme souffrant de perte de mémoire à court terme utilise des notes et des tatouages pour retrouver le meurtrier de sa femme.",
             14.99, 113, 2000, 7),
            (str(uuid.uuid4()), "Comédie", "Astérix et Obélix: Mission Cléopâtre",
             "Les gaulois aident un architecte égyptien à construire un palais pour Cléopâtre.", 13.99, 107, 2002, 11),
            (str(uuid.uuid4()), "Action", "Le Transporteur",
             "Un chauffeur et expert en arts martiaux livre des colis sans poser de questions, jusqu'à ce qu'il brise ses propres règles.",
             15.99, 92, 2002, 8),
            (str(uuid.uuid4()), "Drame", "Sur la route de Madison",
             "Une femme au foyer entame une brève mais intense relation avec un photographe de passage.", 14.99, 135,
             1995, 6),
            (str(uuid.uuid4()), "Science-fiction", "Minority Report",
             "Dans un futur où les crimes peuvent être prédits, un policier est accusé d'un meurtre qu'il n'a pas encore commis.",
             16.99, 145, 2002, 9),
            (str(uuid.uuid4()), "Animation", "Vaiana, la légende du bout du monde",
             "Une jeune fille polynésienne entreprend un voyage pour sauver son peuple.", 17.99, 107, 2016, 14),
            (str(uuid.uuid4()), "Comédie", "Le Prénom",
             "Un dîner entre amis dérape lorsque l'un d'eux révèle le prénom choisi pour son futur enfant.", 13.99, 109,
             2012, 7),
            (str(uuid.uuid4()), "Thriller", "Zodiac",
             "Un dessinateur de presse, un journaliste et des détectives tentent d'identifier le tueur du Zodiaque.",
             15.99, 157, 2007, 5),
            (str(uuid.uuid4()), "Drame", "Requiem for a Dream",
             "Quatre personnes sont détruites par leurs addictions.", 16.99, 102, 2000, 6),
            (str(uuid.uuid4()), "Fantastique", "Edward aux mains d'argent",
             "Un homme artificiel avec des ciseaux à la place des mains tente de s'intégrer dans une banlieue.", 14.99,
             105, 1990, 8),
            (str(uuid.uuid4()), "Comédie", "Supergrave",
             "Deux lycéens essaient d'organiser une fête légendaire avant de partir à l'université.", 13.99, 113, 2007,
             9),
            (str(uuid.uuid4()), "Science-fiction", "District 9",
             "Des extraterrestres réfugiés sont parqués dans des bidonvilles en Afrique du Sud.", 15.99, 112, 2009, 7),
            (str(uuid.uuid4()), "Animation", "Les Nouveaux Héros",
             "Un jeune prodige de la robotique et un robot gonflable combattent un criminel masqué.", 16.99, 102, 2014,
             10),
            (str(uuid.uuid4()), "Drame", "Spotlight",
             "Des journalistes enquêtent sur des cas d'abus sexuels commis par des prêtres catholiques à Boston.",
             15.99, 129, 2015, 6),
            (str(uuid.uuid4()), "Western", "Django Unchained",
             "Un esclave libéré s'associe à un chasseur de primes pour sauver sa femme d'un propriétaire de plantation cruel.",
             17.99, 165, 2012, 8),
            (str(uuid.uuid4()), "Action", "Speed",
             "Un policier doit empêcher une bombe d'exploser dans un bus qui ne peut pas ralentir sous 80 km/h.", 14.99,
             116, 1994, 7),
            (str(uuid.uuid4()), "Comédie", "The Grand Budapest Hotel",
             "Les aventures d'un concierge légendaire et de son protégé dans un célèbre hôtel européen.", 16.99, 99,
             2014, 9),
            (str(uuid.uuid4()), "Science-fiction", "Her",
             "Un homme tombe amoureux d'un système d'exploitation doté d'intelligence artificielle.", 15.99, 126, 2013,
             6),
            (str(uuid.uuid4()), "Drame", "Le Loup de Wall Street",
             "L'ascension et la chute d'un courtier en bourse qui a bâti sa fortune sur la fraude.", 18.99, 180, 2013,
             10),
            (str(uuid.uuid4()), "Animation", "Persepolis",
             "Une jeune fille grandit en Iran pendant la Révolution islamique.", 15.99, 96, 2007, 7),
            (str(uuid.uuid4()), "Thriller", "L'Affaire Dreyfus",
             "Un officier français d'origine juive est injustement accusé d'espionnage et condamné.", 16.99, 132, 2019,
             8),
            (str(uuid.uuid4()), "Comédie", "Les Bronzés",
             "Un groupe de vacanciers dans un club de vacances vit des aventures cocasses.", 13.99, 87, 1978, 11),
            (str(uuid.uuid4()), "Fantastique", "Le Seigneur des Anneaux: Les Deux Tours",
             "La Communauté de l'Anneau est dissoute tandis que Frodon poursuit sa quête.", 19.99, 179, 2002, 13),
            (str(uuid.uuid4()), "Drame", "La Haine",
             "Vingt-quatre heures dans la vie de trois jeunes d'une banlieue parisienne après une nuit d'émeute.",
             14.99, 98, 1995, 7),
            (str(uuid.uuid4()), "Science-fiction", "Terminator 2",
             "Un cyborg du futur est envoyé pour protéger un jeune garçon contre un assassin plus avancé.", 16.99, 137,
             1991, 9),
            (str(uuid.uuid4()), "Animation", "Frozen",
             "Une princesse part à la recherche de sa sœur dont les pouvoirs glaciaux ont emprisonné le royaume.",
             17.99, 102, 2013, 15),
            (str(uuid.uuid4()), "Comédie", "The Big Lebowski",
             "Un flemmard est pris par erreur pour un millionnaire et se retrouve impliqué dans un enlèvement.", 14.99,
             117, 1998, 8),
            (str(uuid.uuid4()), "Aventure", "Mad Max",
             "Dans un futur post-apocalyptique, un policier se venge des motards qui ont tué sa famille.", 15.99, 93,
             1979, 6),
            (str(uuid.uuid4()), "Drame", "La Vie des autres",
             "Un agent de la Stasi surveille un écrivain en Allemagne de l'Est et devient de plus en plus absorbé par sa vie.",
             16.99, 137, 2006, 5),
            (str(uuid.uuid4()), "Science-fiction", "Gravity",
             "Deux astronautes tentent de survivre après la destruction de leur navette.", 18.99, 91, 2013, 9),
            (str(uuid.uuid4()), "Action", "Jason Bourne",
             "Un ancien agent de la CIA tente de découvrir son véritable passé.", 16.99, 123, 2016, 7)
        ]

        requete_insertion = """
        INSERT INTO produits (id, categorie, nom, description, prix, longueur, annee, en_stock)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        """

        cursor.executemany(requete_insertion, films)
        connection.commit()

        print(f"{cursor.rowcount} films ont été insérés avec succès !")

except Error as e:
    print(f"Erreur lors de la connexion à MySQL : {e}")

finally:
    if connection.is_connected():
        cursor.close()
        connection.close()
